// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP_nwfXn-NB0u_02Ob0oojcqAmChR1FBY',
    appId: '1:398688401818:web:e8665d23971370a86ee223',
    messagingSenderId: '398688401818',
    projectId: 'hridoy-ecc48',
    authDomain: 'hridoy-ecc48.firebaseapp.com',
    storageBucket: 'hridoy-ecc48.appspot.com',
    measurementId: 'G-4SYNPE86K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIwiy1fIo3IXABIbJjlUr08zkI2bATPxA',
    appId: '1:398688401818:android:ab769b169cb3ff1a6ee223',
    messagingSenderId: '398688401818',
    projectId: 'hridoy-ecc48',
    storageBucket: 'hridoy-ecc48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8oE7Yf2-MVMhUkc7YZ-Nb_MRVYISYEWc',
    appId: '1:398688401818:ios:40fe12559ce312f26ee223',
    messagingSenderId: '398688401818',
    projectId: 'hridoy-ecc48',
    storageBucket: 'hridoy-ecc48.appspot.com',
    iosBundleId: 'com.example.khelaHobe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8oE7Yf2-MVMhUkc7YZ-Nb_MRVYISYEWc',
    appId: '1:398688401818:ios:14afceb7c6d004276ee223',
    messagingSenderId: '398688401818',
    projectId: 'hridoy-ecc48',
    storageBucket: 'hridoy-ecc48.appspot.com',
    iosBundleId: 'com.example.khelaHobe.RunnerTests',
  );
}
